### ISSUE TITLE
Update filter view?

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#290] opened 2023-03-08 11:24 UTC
- Is that the filter view we want to have for the next study?  The three categories might be a bit confusing / arbitrary.
- Do we want / need to persist the filter across the insights and map view?

![Simulator Screen Shot - iPhone SE (2nd generation) - 2023-03-08 at 12 23 27](https://user-images.githubusercontent.com/2930332/223701334-d0aabc7f-74d5-41fc-afcd-04b2dba67510.png)

**Comment by schrooom** [comment] 2023-05-16 06:57
duplicate of #302

**Closed as completed by schrooom** 2023-05-16 06:57 UTC
Labels: duplicate
